### ISSUE TITLE
[Idea] Increase"Smart downloads" limit on YT Music

### ISSUE THREAD

**Issue by Fusseldieb** [YTVanced/Vanced#1037]
I know that YT Music is just a side project, however it would be nice to have the Smart downloads limit of 500 tracks increased to 10000 or something like that.

I am currently using a YT Music Premium subscription with YT Music Vanced, so the downloads work, but only up to 500 :c

Would increasing the slider "limit" make it work? Would happily test it :)

Don't know if that's possible, but would be amazing!

**Comment by milindgoel15** [comment]
Ask Google to increase the limit for you.

**Comment by Fusseldieb** [comment]
@milindgoel15 Why so mean? 

I've seen that this isn't your first time being this mean on the Issues, since I searched a bit before posting it.

**Comment by milindgoel15** [comment]
Lol you do realise vanced doesn't touch anything related to video or music downloading. Asking the limit to be increased and saying "I am mean" is pretty hilarious 🤣🤣.

I asked kevin about this already and yes there's a possibility we do it. But as again, we have no intentions to touch anything related to video/music downloading. Rest upto oizaro for doing it.

**Comment by Fusseldieb** [comment]
> [...] and saying "I am mean" is pretty hilarious 🤣🤣.

Well, you didn't give any expalation on why and just told me "I should ask Google". 
Google is such a big company that any complaints mostly go down a big black hole, unless it's something big, and we all know that.
That's why I saw it as being mean.

But yea...

> vanced doesn't touch anything related to video or music downloading

I know that the Vanced team doesn't touch core functionalities of the app. That's also why downloads doesn't work unless paid, etc.

My question was specifically frontend-wise, if increasing the slider value maybe makes the YT Music download more than it would originally. Maybe it's not that easy, I really don't know.

A first step would maybe be using a rooted phone and changing this variable at runtime and see what it does. There are some apps for that, I would need to search for those to do the test.

**Comment by milindgoel15** [comment]
I suggested to ask Google because you already know vanced doesn't touch anything related to it, it directly mean it's upto google to change this limit for you and all those users who use it, not us. It's pretty straightforward imo. But anyways
>Well, you didn't give any expalation on why and just told me "I should ask Google".

The limit is yes could be changed. We just do not encourage it nor I personally like the idea to change it. It could bring google eyes on vanced as we would be touching their core function. If this does work and google doesn't care about it, then yes we are in good direction else you know what Google can do. So now it's upto oizaro to do it.

**Comment by Fusseldieb** [comment]
Now it makes more sense, thanks!
