### ISSUE TITLE
[Idea] Apply the old resolution picker to the Video Quality Preferences menu.

### ISSUE THREAD

**Issue by CarsondaCoolest** [YTVanced/Vanced#1097]
**Description**
Issue #790 addressed the unwanted change to video quality settings in the video player, but the default resolution settings did not have this same change applied. For the sake of being able to set a default resolution, I am suggesting that the same change be made to the Video Quality Preferences menu in the settings.

_![Screenshot_20210720-172134](https://user-images.githubusercontent.com/59584865/126405321-1c98cb5e-e980-48e6-9fd7-db45786d72f3.jpg)_
![Screenshot_20210720-175414](https://user-images.githubusercontent.com/59584865/126405447-46e427e8-799a-4402-9a5f-23df66be2dcd.jpg)
(Note, the text following "go to" (which is unreadable due to my theme) is a link to the settings menu I am discussing.)

**Comment by cprcrack** [comment]
Yes please, just give us the option to choose our desired exact resolution for every video. In my case I just want 720p, always, for every video, both on Wi-Fi or mobile data, and I just can't manage to get that because of the new silly options.

This feature is essential. 720p is the best compromise for me regarding quality (I can't really distinguish 1080p from 720p on my phone's screen) and time to load the video, fast-forward and such, as well as battery usage. which is much lower in 720p vs 1080p or 4K.

**Comment by milindgoel15** [comment]
The feature you are requesting is already present in vanced for 3+ years. Go to vanced settings > video settings and set your preferred video quality to 720p that you want.

Meanwhile the idea of the OP is pretty redundant since he actually wants the video quality preferences to have the feature which lets him choose the default quality when playing videos from all the video quality options (_if I am wrong in interpreting your issue, then do tell_). So please refer the first part of this msg.

**Comment by cprcrack** [comment]
We'll I'm a new user to Vanced and one thing I can tell you, I would have never guessed that there is a "Vanced settings" menu right at the bottom where the uninteresting settings (such as version number and such) usually are, specially as there is already a "Video quality settings" at the top.

It would make much more sense to have the "Vanced settings" just on top of the Settings menu, or at least linked from the stock settings menu, or highlighted in some way. After all if one downloads Vanced it's probably going to like knowing about the customizable settings to take advantage of it, and currently they are just too easy to miss. I believe this is what also happened to OP, which proves my point.
