### ISSUE TITLE
[Bug] Can't scroll through recommended videos 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1121]
**Bug description**
Can't scroll through recommended videos below the currently playing video in the vertical view. It just get stuck and when I scroll to go down it goes up or get reversed and scroll up acts as scroll down. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a random video
3. Watch videos for sometime, an hour more
4. The reported beahviour can occur 

**Expected behavior**
You should be able to scroll through the reccomeneded videos down below when player is playing videos in the vertical mode and not end up in a stuck state as my bug description says. 

https://user-images.githubusercontent.com/29215437/127233879-24697471-fc40-4f85-902b-871a0a78eea0.mp4

**Comment by milindgoel15** [comment]
As far as we know, it's yt bug. But try reinstalling.

**Comment by milindgoel15** [comment]
have you tried it yet?

**Comment by Mimicthis** [comment]
> have you tried it yet?

I have tried it but it doesn't work.

**Comment by milindgoel15** [comment]
Check if this issue happens on v16.29.39

**Comment by Mimicthis** [comment]
OK, when will the update come?

**Comment by Mimicthis** [comment]
Rule 1: Don't be bitchy.

**Comment by gghhkm** [comment]
Xfile has to patch it later.

**Comment by Jackiealucard** [comment]
Hi there i have a probelm i cant use the latest youtube music vanced update when ever i do it crashes it might because im using a samsung j7 sky pro if you could fix this that would be awsome also i was wondering if you could make it whare you could downowd music on the app for offline play avible again for got what update had it but there was an update not to long ago that let me do it. Senserly jackie alucard if you do get any of this done i would be gratfull if yall dmed me on discord about it at jackiealucard#7035 thx

**Comment by Mimicthis** [comment]
Bump

**Comment by NotByMe** [comment]
Simply solve it by clearing app cache. The way of handling app caches, especially after using for a long time continuously, is poorly coded and thus the culprit, since it can be reproduced on official YouTube app.

**Comment by GKid94** [comment]
@milindgoel15 I also still have this problem on the latest YouTube Vanced and regular YouTube, is it possible to fix it in Vanced?

**Comment by Mimicthis** [comment]
Hihhihi, see?
