### ISSUE TITLE
YT Vanced Music casting to Google Speaker

### ISSUE THREAD

**Issue by Zerodoxalts** [YTVanced/Vanced#1194]
Whenever I try to cast a music video to my JBL google assistant speaker. It tells me I don't have premium.

Couldn't tell if this is a known issue. Otherwise it is now.

**Comment by milindgoel15** [comment]
Because vanced is **NOT** YT premium. And it will never be. Pay Google first to use that feature.

**Comment by Zerodoxalts** [comment]
Isn't Vanced the "free" premium??

**Comment by milindgoel15** [comment]
No it's not. Just because vanced gives us ad blocking and background playback, it doesn't make it YouTube premium. Vanced was made with only ad blocking and background playback in mind by the dev back then. It became public due to its success 

Ad blocking existed long before(in different variants by many devs) YouTube played their games and introduced YouTube red to earn money out of ads. There's a full information already on the internet on XDA, telegram, discord written, explained tons of times.

**Comment by Zerodoxalts** [comment]
Alright, thank you for the explanation.
