### ISSUE TITLE
[Idea] Please do not get rid of the dislike count. 

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#1377]
**Description**
Title.

**Comment by Square365H** [comment]
You know its google who makes that decision right?

Im saying this because right now I cannot see the dislike count from my main google account. Apparently its being part of their "experiment". I haven't seen anyone else with this issue.

Could it be possible to add a bypass to the dislike count? Like adding a proxy account to retrieve the dislike count and display it on the "experiment" account? Its super annoying and google hasn't answered to my inquiry yet.

**Comment by Diridibindy** [comment]
Either way if google commits, there is no way to bring it back.

**Comment by leodoi3** [comment]
Someone should create an independent dislike database + browser extension that will work on the same principle as SponsorBlock. It might be even possible to fetch and archive the current dislike counts, since API should remain working till December 13th.

**Comment by milindgoel15** [comment]
Tell Google

**Comment by PeterNjeim** [comment]
> Tell Google

Is there no way to change the text in the UI? Accessing dislikes is possible via the API until December 13th, so if it's possible to edit the text in the UI, you would be able to show the count. Do you know the details of this?

**Comment by milindgoel15** [comment]
> Is there no way to change the text in the UI?
We don't own youtube sir.
