### ISSUE TITLE
[Idea] Android 12 Themed Icons

### ISSUE THREAD

**Issue by tomc128** [YTVanced/Vanced#1393]
**Description**
It would be great if YouTube Vanced offers support for Android 12's themed icons. By doing this, the regular YouTube app could be replaced on the homescreen whilst maintaining the clean aesthetic provided by themed icons.

![Screenshot_20211116-202709](https://user-images.githubusercontent.com/43298139/142060793-9e2b989c-8bdb-412e-93b9-b20cfcad1915.png)

On the left is the YouTube themed icon. Vanced could implement something similar.

**Comment by milindgoel15** [comment]
We are closing this issue since it will be rolled out with future vanced release.

However, it won't work on android 12 as Google restricts themed icon support for Google stock apps only. 

The themed icons will only work on Android 13 as of now. Google may push a patch through security update to make android 12 support third party apps. But there's nothing we do it on our side. 

Alternative ways to use themed icon would be to use third party launcher with Monet icon sets.
