### ISSUE TITLE
[Bug] Youtube Vanced Install Fails - INSTALL_FAILED_VERSION_DOWNGRADE on Xiaomi Phone

### ISSUE THREAD

**Issue by SucculantMeal** [YTVanced/Vanced#1427]
**Bug description**
Installation of Youtube Vanced Fails on Device. ERROR: "Installation failed becuase the user tried to downgrade the package. Uninstall updates from the stock app. then try again." Failure INSTALL_FAILED_VERSION_DOWNGRADE

MIUI optimisation is disabled
USB Debugging is ON
Install via USB is ON
Verify apps over USB is OFF

i have tried resetting the phone to factory settings with no success 
i have followed the troubleshooting guidlines 
i have tried to uninstall / Update and freeze the Youtube app with no success

**Variant**
Root

**Vanced version**
16.29.39

**Android version**
Android 11 MIUI 12.5.5

**Device**
Xiaomi 11 Lite 5G NE 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Download
3. Click on Install

**Expected behavior**
Should install Youtube Vanced but Fails with error as described above

[20211030_124728.log](https://github.com/YTVanced/Vanced/files/7625465/20211030_124728.log)

**Comment by milindgoel15** [comment]
This error is caused by the official YouTube app being present in your OS. When you try to install vanced, the vanced manager detects you have official YouTube present and throws that error because the version of YouTube is higher than vanced. 

The solution to this is to use debloater magisk module to debloat (aka fully uninstall) official YouTube from the system. The instructions to debloat method can be found in [this guide](https://telegra.ph/Installation-for-Vanced-09-01#How-to-uninstall) (check for debloat method).
