### ISSUE TITLE
vanced manager and micro g issue

### ISSUE THREAD

**Issue by hgunduz295** [YTVanced/Vanced#1464]
**Bug description**
root method not installing the app
non root method dont sign in to google.

**Variant**
Non-Root/Root both
root variant dont installing youtube vanced apk
unroot variant have micro g issue dont sign in to google 

**Vanced version**
16.29.39 
 
**Vanced Manager version**
2.6.2(Crimson)
**Android version**
 Android 11 

**Device**
 Samsung Galaxy A50

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'youtube vanced download button'
3. and installing error 
4. ı switch non root method
5. and install microg and youtube vanced 16.29.39
6. open the youtube vanced 16.29.39 and sign in 
7. ı enter my username and password and see   login error. 

**Expected behavior**
in root method probably must  install the vanced app
in non root method probably must login to google perfectly.

**Comment by milindgoel15** [comment]
Such a good and fantastic report 👍👍👍

Refer [troubleshooting](https://telegra.ph/Troubleshooting-for-vanced-03-19) and find the solution for the problems you are having for either root or non-root which you wanna install. Since you didn't bother providing actual error, we can't help you much. 

Troubleshooting has all the solutions for all problems. Consider reading that.

**Comment by hgunduz295** [comment]
nevermind i just   install  vanced manager  by X1nto apk  and worked
