### ISSUE TITLE
[Question] videos cannot be downloaded now if you don't have premium

### ISSUE THREAD

**Issue by Relected** [YTVanced/Vanced#1475]
**Description**
so I had a out 70 videos downloaded on Vanced, recently a pop-up shows up whenever I try to download a video telling me that I have to pay for premium whenever i try to download videos 720p and above (360p and 144p were fine) 

now every downloaded video that I have no matter the quality tells me that I have to make a payment to watch it, even if I just downloaded the video a couple seconds ago it forces me to pay for premium to watch any video offline (I tried a VPN on different countries, didn't work)

**Comment by milindgoel15** [comment]
So? Get yt premium then

Vanced != YT premium. We won't ever make video downloader for u

**Comment by Relected** [comment]
@milindgoel15 at least take some inspiration from NewPipe

**Comment by milindgoel15** [comment]
Nope we won't. We don't want shut down notice from Google. The reason newpipe survives with downloader is that its not made on top of stock yt. They have their own code.

**Comment by gghhkm** [comment]
@Relected it's illegal to break DRM.

**Comment by Relected** [comment]
@gghhkm YouTube has DRM?

**Comment by gghhkm** [comment]
> @gghhkm YouTube has DRM?

Yes. Google has implemented DRM into the downloader, granted it's pretty simple DRM but it allows Google to shut down just about any YouTube mod that breaks it.  Maybe a mod based in Russia or something can get around this because their country does care to take action, but Vanced is based in the US and so there's no chance.
