### ISSUE TITLE
[Idea] default playing option

### ISSUE THREAD

**Issue by Nilcouv** [YTVanced/Vanced#1516]
**UserStory**
- as a user, I would like to set a default definition for the video in the settings, so that I don't have to manage it for every video I play
- as a user, I would like to set a default playback speed in the settings, so I don't have to manage it every time I play a video
- as a user, I would like to set a FPS limiter in the settings, to limit the data and energy consumption of my device

**Suggestions**
- Add dropdown menu in the setting allowing the user to select a default definition (480p, 720p, etc. the default option of YouTube is awful) 
- Add a slider and a text field in the setting allowing the user to define a default playback speed for the video (... 1.5, 1.6, 1.7, ...)
- Add a switch button "remember the last speed" in the settings overriding the default speed option to allow a more organic playback speed management
- Add a switch button "limit at 30tps" in the settings to force the download of videos in 30 fps (same as "allow 60 fps" in the chrome addons "improve youtube!")

**Comment by TheAmazingBen100** [comment]
The first two already exist in Vanced and have existed for quite a while. Make sure you're on the latest vanced versions to set those settings. Latest version is available at [https://vancedapp.com.](https://vancedapp.com)
As for the last one, ask google instead. It can't be done because on 60fps video, the highest non-60 resolution is 720p, and viewing 60fps video at 720p30 is only available on some older devices.
