### ISSUE TITLE
Skipping videos would be nice

### ISSUE THREAD

**Issue by cjcaf1995** [YTVanced/Vanced#1530]
-

**Comment by Itay123TheKing** [comment]
Or they could just modify the app such that the prompt won't appear in the first place....

**Comment by TheAmazingBen100** [comment]
The "are you still watching" prompt is a server side component, vanced can't do anything about it

**Comment by erik9012** [comment]
> The "are you still watching" prompt is a server side component, vanced can't do anything about it

I can pass them with Userscripts on laptop so why not with android apk

**Comment by milindgoel15** [comment]
> I can pass them with Userscripts on laptop so why not with android apk

If you are thinking it's so easy to do it and android and web share the same code, consider coding it. 

Android code is much different from pc and is written in litho and obfuscated code. Plus the extensions don't work on android the they do on web. If you have some api, then yes could be possible but too much work. If you can do it, do it

**Comment by Ascor8522** [comment]
> If you are thinking it's so easy to do it and android and web share the same code, consider coding it.
> 
> Android code is much different from pc and is written in litho and obfuscated code. Plus the extensions don't work on android the they do on web. If you have some api, then yes could be possible but too much work. If you can do it, do it

Chill out. Pretty sure that's not what he meant.

Like, if there is a way to bypass that "server side check" on another platform (like on the web), then it means it's doable and could be done in Vanced as well. Nobody said it needed to be a JavaScript userscript.

If the Vanced team modified the app to add new features and settings, then they can probably also modify the app in a way that the "Are you still watching" prompt always returns true (if this check is even requested by the server in the first place, otherwise you can just make it never appear in the first place and not pause the song).

**Comment by milindgoel15** [comment]
> Pretty sure that's not what he meant.

He did meant it. 
> I can pass them with Userscripts on laptop so why not with android apk

This line does say that he thinks android apk share the same code as website is. 

I was only trying to say that it is very difficult to achieve it since yt code is much obfuscated and written in litho. If the check is done client side, then it might get considered. Otherwise no. 

The only priorities for next release is to bring ryd and ads whitelisting.

**Comment by erik9012** [comment]
Am sorry if I attacked people. I wrote it probably bad so I’m sorry. I wanted to say it, because if it’s possible with a Userscripts it doesn’t sound like it is impossible to do without it. I fully understand it if Vanced won’t integrate it.
