### ISSUE TITLE
[Bug] Tapping full screen only goes full screen on second try (stock unmodded device, official YT client doesn't exhibit this behavior)

### ISSUE THREAD

**Issue by awesomeferret** [YTVanced/Vanced#1680]
**Bug description:** 
When using a clean install, things work as they should. Then, it will randomly decide to exhibit the behavior that I will describe in a moment, and will do so in a 100 percent reproducible manner going forward once it has "decided" to exhibit this bug.

The unwanted behavior is this: when you tap the full screen icon, no rotation or full screen will happen. Instead, it very briefly goes "full screen" in portrait mode (black bars on top and bottom) with the "rotate" thingy popping up, then immediately goes back to portrait view. The second time you tap full screen, it works as expected. Having it take two tries to go full screen is very strange, and it's ALWAYS two times. This issue was accidentally closed due to a misunderstanding, so I have reposted this (and done so properly, I guess on mobile there isn't this template). This cannot be a "ROM issue" as the closer said, since the same version of the official YT client exhibits no such issue and goes full screen perfectly every time. Older versions of Vanced also do not  have this issue, so closing it and saing "ROM issue" was clearly an error.

I thought this may be related to my choosing the "wide search bar" feature or "copy button" feature, but I disabled those and the bug still persists.

**Have you read vanced guides already? (YES)**

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
Vanced manager

**Android version:**
Android 8

**Device:**
LG V20, completely stock unmodified device (thus probably not a ROM issue?)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Tap on video
3. tap full screen icon.
4. Full screen fails
5. tap full screen again
6. transition to full screen is successful.

**Expected behaviour:**
Video should enter fullscreen on first tap. This is NOT a "ROM issue" because the same version of the official YouTube app handles fullscreen perfectly.

I would provide logs if I could figure out where they are stored. Please let me know where so I can update this with logs.

**Comment by milindgoel15** [comment]
_ROM issue_

**Long answer:**
Because you can't understand what these 2 words mean or because you think it's rude to say this when it's not. 

This is an issue where a part of OS bugs starts affecting applications to cause issues. This is one of those issues where the source cause of the bug comes from the OS. 

Sure you can say, your OS is a stock, unmodified ROM, but is it really stock? Do you receive updates directly from Google? Is your software maintained by google itself? or does LG puts its own patches on top of AOSP code?

Stock only means that your software is near close to Google pixel OS or bare AOSP code. Every OEM whether being Xiaomi, Samsung, Huawei, LG, Oppo, Oneplus and so on puts its own stuff and customize the AOSP to bring you a different version of android in the form of MIUI, OneUI, emui, Lg, funtouch OS, Oxygen os respectively and so on. Such skins are heavily modified from the ground up which can cause bugs in an unexpected way. 
Sure it doesn't mean that we will start saying ROM issue to everyone who owns such devices. But did you look not every bug happens on every device? did you look that LG is already discontinued and you are still on the oldest version of android where google has already started releasing developer preview for Android 13? 

You might be facing issues with it, we get it. We get that you are not facing such an issue on the official version of the YouTube app which you didn't even specify which exact version number is it. But it doesn't mean you will start complaining about it by saying we are rude for not giving you much attention. We don't expect our users to start complaining if we say it's a ROM issue. You can see what wordings did you use against us. If we said "ROM issue", speak about why it is causing it? What can you do on your behalf to fix it? And if it isn't a ROM issue, help the vanced team by providing logs.

(Also, minor thing but very important, you also never bothered to put #1674 in the bug report template we provided. How did you expect us to help you in a more intuitive/elaborative way?)

**Comment by nyanpasu64** [comment]
I'm getting this bug on Pixel 4a running official Pixel OS, on Android 12 and 13.
