### ISSUE TITLE
[Enhancement]Repositioning of allow/disallow ads button]

### ISSUE THREAD

**Issue by kryptobolt200528** [YTVanced/Vanced#1736]
**Description**
Hey thanks devs for adding the allow ads feature for specific channels...
I am really happy that you listened to us...
However I feel that the current implementation of the "ads" button is kinda ugly...it covers a lot of space and ruins the overall aesthetic..

![IMG_20220309_101441](https://user-images.githubusercontent.com/72438196/157374438-f06c9f0d-5e9a-493d-a158-c44352883236.jpg)

I request it to be repositioned beside the subscribe button with suitable color scheme..
I also think it overal makes more sense for it to be positioned besides a channel name/subscribe button

**Comment by milindgoel15** [comment]
Placing that to the left of subscribe button would be make content in that region too bloated since there's not much space left. 

You can however enable extra toggles in action bar to make it look less weirder. 

Just like this:
![IMG_20220309_115035.jpg](https://user-images.githubusercontent.com/45682747/157384035-e681a2e5-8e07-43f7-b78c-1e02ad2f80de.jpg)

The current placement is still subject to change and can get changed if we find any better placement for it. I will close this issue but don't worry I will forward this idea to dev too.

**Comment by kryptobolt200528** [comment]
I understand but i still think it can be placed over the left by widening the subscribe panel a little bit 
and reducing the sizes...also it can be just a text like the subscribe button...just ADS or ~ADS~..

**Comment by milindgoel15** [comment]
> I understand but i still think it can be placed over the left by widening the subscribe panel a little bit and reducing the sizes...also it can be just a text like the subscribe button...just ADS or ~ADS~..or maybe it can be in the first panel(we could slide to access it)

I had asked dev and he declined it.
