### ISSUE TITLE
[Bug] Cannot use pip mode

### ISSUE THREAD

**Issue by Reator** [YTVanced/Vanced#197]
Cannot use pip mode in miui

**Comment by MedicOP** [comment]
Same problem here. This issue has been happening since updating to MIUI 11 or 12.

The OP fails to mention that it only happens when using gestures instead of the buttons. The PIP shows up fine when clicking a link in a video description or using the "Back" gesture until you reach the home screen. The only one that doesn't work is when you use the "Home" gesture by swiping up.

**Comment by gkp1** [comment]
**Picture-in-Picture not working
The way PiP works is controlled by your operating system. If it's broken, there's nothing we can do, so please don't report PiP related issues.
Page 9/9•08/11/2020**

**Comment by MedicOP** [comment]
It's not broken though, it's just not being activated when using the "Home" and "Multi-task" gestures. It works fine when opening a link or using the back gesture

**Comment by suraj735541** [comment]
My device is not miui still facting this proble.m.
