### ISSUE TITLE
[Bug] Pull down refresh feed not working

### ISSUE THREAD

**Issue by BaIanced** [YTVanced/Vanced#252]
**Bug description**
Trying to refresh feed by pulling down doesn't work after first launch. This is directly related to the "general ui adblock." Refresh works fine when this setting is disabled but ad is shown on the main feed as first element.

**Variant**
NonRoot: No
Root: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
OnePlus 6T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Pull down on feed to refresh (doesn't work after first time opening app)
3. Disable general ui ad block setting
4. Force close app
5. Open app
6. Pull down on feed to refresh (it works)

**Expected behavior**
It should refresh feed. Aka populate with new list of videos.

**Comment by milindgoel15** [comment]
known issue as its a litho bug explained below.
Litho has their own implementation of RecyclerView (it's used as a parent group for multiple listings inside it since it can recycle view layout and consume less memory) and Swipe-to-refresh layout. For whatever reasons, when the height of first item in RecyclerView is set to 0, Swipe-to-refresh breaks. This can be fixed if the first element is set to height of 1 instead of 0. I've created a sample repo which contains everything needed to reproduce the bug: https://github.com/X1nto/LithoRecyclerSample

https://github.com/X1nto/LithoRecyclerSample/blob/master/app/src/main/java/com/xinto/srltest/CardGroupSpec.java here everything is commented out

**Comment by fire17** [comment]
> 2\. Tap on any suggestions/filters on top of the home tab and pull down to refresh will start to work

sweet thank you :heart:

**Comment by xectrone** [comment]
In App, click your user circle top right corner. Click settings > vanced settings > ad settings > uncheck general layout ad removal
