### ISSUE TITLE
[Bug] vanced show update youtube notification on startup

### ISSUE THREAD

**Issue by eldon97** [YTVanced/Vanced#313]
it's not necessary for vanced.. 
![IMG_20210103_121413](https://user-images.githubusercontent.com/19554521/103472251-06508f80-4dbe-11eb-9779-3c80a434ea03.jpg)

**Comment by gghhkm** [comment]
It's not a bug. You just can't remove it.

**Comment by eldon97** [comment]
> It's not a bug. You just can't remove it.

yeah we can't remove it, that's why I think this is a bug for the vanced app because the update is for original youtube app in play store.. it will be better if the developers could get rid of this notification in the vanced app.

**Comment by gghhkm** [comment]
> > It's not a bug. You just can't remove it.
> 
> yeah we can't remove it, that's why I think this is a bug for the vanced app because the update is for original youtube app in play store.. it will be better if the developers could get rid of this notification in the vanced app.

It's not a bug.
It shows up because Vanced is based off of an old Stock Youtube and that gets detect and triggers the prompt; it happens in stock as well.
It is not remove able.
It's not like the Dev team can do whatever they want, some things require access to the source code of stock; which they will never have.

**Comment by eldon97** [comment]
duplicate of #279
