### ISSUE TITLE
[Idea] disable recommendation/homepage and trending

### ISSUE THREAD

**Issue by Homura82567** [YTVanced/Vanced#352]
I think it is similarity to disable of create button. In PC there is some similar plugin call "remove recommended videos, comments " I really hate YouTube keep recommending many videos I am not interested. Alought sometime some are funny, but most of the annoying

**Comment by Forkingss** [comment]
Yes! Would be great this feature of hidding all the Homepage videos! :)

**Comment by triplenman** [comment]
### I would really like to be able to hide all video recommendations under a video
**I only watch my playlists and only use the Library section, so I’m very distracted by the video recommendations and another unnecessary sections.**
Because of this I have to use YouTube through the browser and block unnecessary sections through extensions =(
This is really necessary! In the survey, my friends and familiars also confirmed this. Such things have been repeatedly discussed on some forums and discussed ways to get rid of unnecessary in the interface.
It would be ideal to **add the ability to hide "Video recommendations under a video" together with sections "Home", "Explore", "Subscription"** [in the settings where it is possible to hide the "Create button" and "Cast button"]. With these changes, the application would be perfect and there will be no need for a browser with extensions!
Thank you very much for your work!

**Comment by jaambo** [comment]
I support this idea. This is also important to me. Recommendations annoy me a lot!
