### ISSUE TITLE
[Question] Get YT Vanced Root APK WITHOUT MANAGER

### ISSUE THREAD

**Issue by dragonBall561** [YTVanced/Vanced#374]
**Description**
I have a ROM so YouTube doesn't came PreInstalled by default, and it also doesn't come with the GAPPS I use. Is there a way to get YouTube Vanced Root Version working on a ROM without YT (regular, not Vanced) NOT already installed?

**Comment by Vendicated** [comment]
Yes there is, by using the [official microG](https://github.com/microG/gmscore) rather than our fork of it. If you search for microG in the Magisk repo you will find a script to easily install this. 

Note that this only works if your phone supports signature spoofing. Otherwise simply use nonroot, there really isn't much of a difference

**Comment by dragonBall561** [comment]
Great thanks!
