### ISSUE TITLE
[idea] preferred subtitles 

### ISSUE THREAD

**Issue by JasonLim25** [YTVanced/Vanced#382]
**Description**
I have a small suggestion for the vanced, not sure whether it is accepted or not..
When watching a video there will be subtitle right, and some video has different wide range of subtitle, I was wondering is it possible to have a button or a toggle in vanced setting, to set a preferred (or forced a ) subtitle language ( For example English).

The theory is almost the same as forcing the Video resolution to HD , like if there are available subtitle in the video, it will automatically enable the english, even though there are other language, French, Korean etc.

**Comment by Yoongbo** [comment]
I'm surprised this hasn't been a vanced feature since day one.

**Comment by Kurogal** [comment]
If I can add to this, I think you should be able to set an ordered list of preferred subtitles, and it should also distinguish between auto generated subtitles and manually added ones. 

So you can set it like Manual English > Auto English > Manual *insert languages here* > None. 

And also if possible maybe a few wildcard options, like one try to match to manual subs of what YouTube auto subs thinks the video language is in.

I always like to have subtitles on when they're added manually even if it's the same language because there can be jokes or script differences hidden in there, but I don't care for the jumbled mess of auto generated captions on every video, so I'd just be using it to avoid needing to check every video for manual captions, but I'd imagine that the tool itself could help others a lot more than that.
