### ISSUE TITLE
[Idea] option to use old layout video list

### ISSUE THREAD

**Issue by dmack6464** [YTVanced/Vanced#41]
![20200922_002835](https://user-images.githubusercontent.com/29574547/93779678-94b76000-fc6a-11ea-87db-d252ce4a7b51.jpg)
This reminded me that I really am not a fan of giant thumbnails, would be nice to have an option to use the old layout.
Don't mind my cringe video recommendations.

**Comment by HamletDuFromage** [comment]
Please do this if possible. I haven't been updating for months because if that, and after finally giving it a shot today. I'm going to downgrade if that doesn't change
![Screenshot_20201002-034545_Samsung Internet](https://user-images.githubusercontent.com/61667930/94883840-f1392d00-046b-11eb-9dd0-37123b925653.jpg)

**Comment by dmack6464** [comment]
:(

**Comment by KevinX8** [comment]
The old layout is long gone from the apps code, it can't be implemented anymore
