### ISSUE TITLE
[Bug] New logo "wide searchbar" gone again. Great!!

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#459]
**Bug description**
This is like the 4th time I'm reporting this bug, that with every new logo removes the wide search bar feature. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable Wide searchbar in Layout settings
3. It will be removed and you will have no search bar 
![Screenshot_20210215-084747086 (1)](https://user-images.githubusercontent.com/73917917/107919116-18038600-6f6b-11eb-9ed0-49b2e35faf8c.png)

**Comment by Hyperboraeer** [comment]
If you search for "wide search" you see all my other unsolved bugreports. YT is like adding new Logos every week nowadays.
![Screenshot_20210215-085309378 (1)](https://user-images.githubusercontent.com/73917917/107919315-62850280-6f6b-11eb-9b5f-507acf790a5f.png)

**Comment by Hyperboraeer** [comment]
Reddit posts that I created about this bug with tons of upvotes and comments:
![Screenshot_20210215-085629597](https://user-images.githubusercontent.com/73917917/107919525-cad3e400-6f6b-11eb-8906-5a54872b0f28.png)
![Screenshot_20210215-085623212](https://user-images.githubusercontent.com/73917917/107919531-cb6c7a80-6f6b-11eb-897c-718ae382d503.png)
![Screenshot_20210215-085614401](https://user-images.githubusercontent.com/73917917/107919532-cc051100-6f6b-11eb-880a-6b3d1757324d.png)

**Comment by VancedOfficial** [comment]
I've been unable to replicate this issue myself. I tried with the BHM logo back then when people first started reporting but even with VPN to USA, I still couldn't get this logo to show up :/

**Comment by Hyperboraeer** [comment]
@VancedOfficial 
I'm a YT Premium subscriber. Weird thing is in the stock app I don't see the logo. I only see the "Premium" Logo in stock YT app. But in Vanced I see these new Logos every week. As you can see stock yt has only "Premium" logo.
![Screenshot_20210215-112349021 (1)](https://user-images.githubusercontent.com/73917917/107934482-6707e600-6f80-11eb-8c82-d9b6086f40ab.png/

Couldn't you somehow add a new layout setting, that would prevent these logos from appearing? Thanks for your reply.

**Comment by VancedOfficial** [comment]
In order for me to add that kind of setting, I would first need to be able to reproduce this issue. But since I can't get any of those logos to show up, it's really hard to start solving a way to prevent them from appearing :/

**Comment by Hyperboraeer** [comment]
Gotcha. That's really so unfortunate and frustrating. I have no idea how to reproduce it. It just pops up for me. 
However I find it weird that these logos apparently don't show up for everyone. What do you think might cause them appearing for me? Something in my YT or Google settings? I don't think it's possible to disable these logos once and for all within YT/Google account settings.

**Comment by VancedOfficial** [comment]
I'm not really sure. I have the wide search bar enabled and even with VPN to USA, I only get the BHM banner as the first home feed item, the wide search bar is still there.

What I don't have is YT Premium subscription. Can you test if the logo shows up with an account that doesn't have YT Premium subscription (if it's not too much of a trouble with account selector being broken because of MicroG)? Also when you disable the wide search bar, what logo do you have then?

**Comment by Hyperboraeer** [comment]
I will try to test that, and get back to you soon. 
But based on all the upvotes and comments in those reddit posts, I assume that many other people who use wide search bar feature are suffering from this nonsense as well.

**Comment by Hyperboraeer** [comment]
@VancedOfficial I tried to add a free account to vanced, but account selector doesn't work as you mentioned. So testing that is not possible atm. 
Well I'm forced to disable wide search bar when a logo appears because if I don't, I will be unable to search. Because there is no search button anymore. Not even the small default search icon.
And disabled it looks this way. New logo still there:
![Screenshot_20210215-125319898 (1)](https://user-images.githubusercontent.com/73917917/107943329-daaff000-6f8c-11eb-91a1-7e33c3740a12.png)

**Comment by VancedOfficial** [comment]
Can you come to the Discord server and DM xfileFIN? Will be easier to debug there than here.

**Comment by loafylemon** [comment]
I have wide search bar enabled, but I was unable to reproduce this issue despite being connected to US West servers. 

I still have got the promotional ads that relate to that logo so I know the server was chosen correctly, but wide search bar worked just fine, even when I've reinstalled YT Vanced under a constant VPN connection.

Are you sure your Vanced is up to date?

**Comment by Hyperboraeer** [comment]
Yes, it's up to date. I'm unable to reproduce this issue either with a free account since MicroG doesn't work. I'm using a YT Premium account, if you didn't notice. 
But I got in touch with a Vanced dev, and tested older versions which apparently don't have these logos crap.
The issue is still not resolved, but reproducing it might be possible once I can add additional accounts to Vanced (when MicroG works)

**Comment by AinzTheSupremeOne** [comment]
I randomly reproduced this issue while being connected to a US VPN server. I have a free YouTube account, of course. 
![Screenshot_2021-02-22-15-18-28-325_com vanced android youtube](https://user-images.githubusercontent.com/50095635/108691540-a191f580-7521-11eb-92d9-c7c92cbf2be2.jpg)

**Comment by AinzTheSupremeOne** [comment]
And oh, I just played a video, went to pip mode, then came back to the app, the logo turned normal. Then I closed the app, and relaunched it, I saw the same logo again.

**Comment by Harmonie666** [comment]
@AinzTheSupremeOne 
Yes this morning I also had that new logo. It disappeared after a while, when I disconnected from US VPN.
But I really need to use YT with the US VPN. To bypass european censorship which doesn't exist in the US. 
This issue needs to be fixed for people who live in the US, or are connected to a US VPN server all the time, like me.

**Comment by Harmonie666** [comment]
Also I just found this article:
https://9to5google.com/2021/02/07/youtube-bhm-logo/

I want to point out that these logos have been appearing last year as well. Around last winter, there were several new logos.
