### ISSUE TITLE
[Idea]  Option to enable miniplayer on "made for kids" videos...

### ISSUE THREAD

**Issue by cyan-2048** [YTVanced/Vanced#468]
**Description**
Some videos are said to be "made for kids" even though it's not...

Because it is "made for kids" the video is not allowed to be played while in the miniplayer...

![Screenshot_20210218-221441_Reddit](https://user-images.githubusercontent.com/72785466/108369599-b9722c80-7236-11eb-9361-783a887ec9ca.png)

**Comment by AinzTheSupremeOne** [comment]
Wait, why on earth a TWICE song is marked as that 🤔. I don't get the point of disabling miniplayer, perhaps to stop kids from browsing YouTube while watching a video, so that they maintain their focus? Anyway I think a toggle to remove this restriction would be helpful, for adults and of course in that above scenario. I support this. Let's see if the devs can implement this.
