### ISSUE TITLE
[Bug] Youtube Vanced not launching from Google search

### ISSUE THREAD

**Issue by backslashV** [YTVanced/Vanced#488]
**Bug description**
Clicking the video thumbnail from the search results in the Google app directs user to the original YouTube app (install page if you don't have it installed) instead of recognizing Youtube Vanced and opening it there.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11.0 

**Device**
Pixel 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Press mic in the Google search app to identify a song
2. Once the song is found, click on it and observe that it is not opened in Vanced.

**Expected behavior**
The video should open in Vanced if there are no other apps to accept the intent.

**Comment by AinzTheSupremeOne** [comment]
> Expected behavior
The video should open in Vanced if there are no other apps to accept the intent.

No, that's not how it works. And thus is not a bug either. YouTube video results on Google search on android have "YouTube app" intent, so it opens the link in stock YouTube app everytime it is clicked on. The intent can't be redirected to another app because a specific app's package name (stock YouTube's package, in this case) name is defined in the intent. So if stock YouTube is not installed, it would redirect you to YouTube page on Play Store. 

For webpages, a fix would be to use a browser with desktop mode enabled.

And for apps (like assistant, Google), it's not possible to fix because non root Vanced can't modify the behaviour of those apps. Using root version of Vanced would fix it as it has the same package name as stock YouTube. 

And oh, you can try tweaking open by default settings in Android. Select YouTube and set it to ask every time/don't open in the app. It may fix the issues for normal links (without intent).

**Comment by backslashV** [comment]
Thanks for the info. Ya, I wasn't sure whether to classify this as a bug or not.

**Comment by SciLor** [comment]
Shouldn't it be fixable via a replacement app for YouTube to redirect the intent?

**Comment by milindgoel15** [comment]
Non-root uses different package names FYI. And Google is pretty strict as to what package google assistant/voice search can use.
