### ISSUE TITLE
Uneccesary? 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#5]
Black theme is an uneccesary toggle. 
What's the purpose of it if everything is black already? 
![Screenshot_20200904-203950](https://user-images.githubusercontent.com/29215437/92293133-5c511b80-ef21-11ea-821b-948a35bca7da.jpg)

[Idea]

**Comment by VancedOfficial** [comment]
It works the same way as the toggle in General settings for people who don't have system specific settings. It's also used in Pink and Blue theme for overriding a few extra string colors.

**Comment by AdemSof** [comment]
Pink and Blue themes? Is that good to use?

**Comment by animule** [comment]
Pink, Blue, Dark and Black themes are certainly useful because it gives us a choice. I like the Blue theme but it can be overwhelming, same for Pink. My gF loves the pink but after a while she turns it off... But she will not go back to regular Youtube app because it does not have this choice. Most of my devices have the DARK theme installed. I only wish they could ALL be choices in ONE Vanced App.

**Comment by AdemSof** [comment]
Thank you so much on the reply. How do you even get vanced to be in that color?

**Comment by gghhkm** [comment]
> Thank you so much on the reply. How do you even get vanced to be in that color?

the Pink & Blue theme  has been discontinued.
