### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by sandiaGG** [YTVanced/Vanced#594]
**Bug description**
I got a problem with my youtune VANCED. Every time i try to open the aplication i have an error saying " no connection" i tryied : resseting my phone. Reinstalling the apss and even switching the acounts..nothing worked

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 and the the older version

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S9+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Ph4nnyBaND1t** [comment]
Im having the same issue.

**Comment by nyanren** [comment]
Same i did evrything yet there's still "no connection". :(

**Comment by gghhkm** [comment]
***General fix for everything Non-root:*** 
**`• this will fix most nonroot Vanced related issues`**
`• you can consider this the proper Vanced install method`



**Preparations for clean install**
`• if you've already installed it and have uncommon problems otherwise Skip`
1. Remove the microG account from system settings 
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

**Installation**
1. Make sure you're using Vanced Manager 2.4.0 or above.
(MiUi users disable MiUi optimization too)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use https://dontkillmyapp.com/ if needed.
4. Install Vanced ***15.40.37***  &/or Music (Note : latest music should work without issue now)
5. Login 
6. Update to latest
(MiUi users, you can readable MiUi optimization at this point if you have to)
