### ISSUE TITLE
YouTube Vanced closes suddenly 

### ISSUE THREAD

**Issue by Bills372** [YTVanced/Vanced#603]
It's claimed YouTube Vanced is alternate to YouTube but even my premium YouTube account is not working on YouTube Vanced.... 

When I stream on YouTube Vanced it is stopped after sometime when screen is off. I am Huawei user and now thinking to again go back to android.... 

Hope Vanced tram resolved and addresses my issue timely.

Regards
Bills

**Comment by GKid94** [comment]
I have the same issue on Samsung Galaxy A5 2015

**Comment by gghhkm** [comment]
***General fix for everything Non-root:***
**`• this will fix most nonroot Vanced related issues`**
`• you can consider this the proper Vanced install method`



**Preparations for clean install**
`• if you've already installed it and have uncommon problems otherwise Skip`
1. Remove the microG account from system settings 
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

**Installation**
1. Make sure you're using Vanced Manager 2.4.0 or above.
(MiUi users disable MiUi optimization too)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use https://dontkillmyapp.com/ if needed.
4. Install Vanced ***15.40.37***  &/or Music (Note : latest music should work without issue now)
5. Login 
6. Update to latest
(MiUi users, you can readable MiUi optimization at this point if you have to)

@Bills372 as for your premium account, we don't have many testers with premium if any at all so it's a bit difficult. Also the latest release of Vanced has a issue because google removing APIs that could also cause this.
You can try using 15.43.32 until the next release if need be.

**Comment by Bills372** [comment]
I'm thankful to vanced team who responded my query very timely. I am amazed. However I have few more concerns out of your reply, as follows:

1. You mentioned to use version 15.40.37 which I did and logged in with my other account which is non-premium. My question here is how I would know that premium account issues is solved and that now we can use premium account. Will there be some public news??
2. How and when I will come to know that we can now upgrade to latest release?
3. Is our information with vanced is saved? And who is behind this vanced so we trust with our information?
4. What if APIs are again blocked... Feels like vanced is risky to use.

Thanks,
Bills

**Comment by gghhkm** [comment]
@Bills372 
1. You'd have to test it yourself to be absolutely sure if the premium accounts work unfortunately, because we don't have premium testers. However, there will definitely be an announcement because there are other problematic bugs caused by the same issue it'll fix as well. 
2. There will be a push notification via Vanced Manager, you can also join [The Official Discord](https://discord.gg/tw6YTkCNFD) to get notified faster.
3. No user data is saved with Vanced team, all Non-root user data is handled by Vanced MicroG which is FOSS ( Apache-2.0 License ) found [here](https://github.com/YTVanced/VancedMicroG) and sent directly to Google; no where else. Vanced MicroG even leaves out a lot of user data that's not needed for Vanced to function making it slightly more private than stock youtube.
  3.5 There are quite a few people who've helped Vanced in various ways over the years, but The person who started it all is XfileFin. I recommend not bothering him tho as he's very busy, but if you'd ever want to talk to him you can find him in the Discord @xfileFIN#2811 , you can find most of us there.
4. If the APIs get removed again then we'd get this issue again. I doubt they'll do it again tho because the APIs are important for legacy devices to run stock youtube and removing the APIs broke it for them. We've also notified [MicroG Project](https://github.com/microg) (what Vanced MicroG is based on; also FOSS) about this and hopefully in the future we'll see a version of Microg that can get around this.
  4.5 Vanced has no risk for the end user, just making sure you get it from [Official](https://vancedapp.com) [sources](https://github.com/YTVanced/VancedManager)

**Comment by Bills372** [comment]
Thank you XDA/Github community, you re very cooperative people developers, I like you respond very detailed and timely. Thank you.
