### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by user2471** [YTVanced/Vanced#681]
Youtube Vanced crashes now and currently does not work. This had just occurred after the I installed the latest update..the phone currently being used is a Samsung Galaxy S20 

Please could you look into this issue..thanks

**Comment by gghhkm** [comment]
## General fix for everything Non-root:
• this will fix most nonroot Vanced related issues
• you can consider this the proper Vanced install method



### Preparations for clean install
• if you've already installed it and have problems, otherwise Skip.
1. Remove the microG account from system settings.
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

### Installation
1. Make sure you're using Vanced Manager 2.4.0 or above. SAI method will also work.
(MiUi users disable MiUi optimization too)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use https://dontkillmyapp.com/ if needed.
4. Install Vanced &/or Music
(MiUi users, you can readable MiUi optimization at this point if you have to)
5. Login 
6. Done.
