### ISSUE TITLE
[Bug] Vanced won't run unless you update Google Play Services

### ISSUE THREAD

**Issue by b0ogdan** [YTVanced/Vanced#751]
**Bug description**
I updated yesterday to latest Manager and lasted Vanced version. YouTube won't run unless you update Google Play Services. 
I checked and everything is updated in Google Playstore.. 

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11.0 - Android R

**Device**
Google Pixel 3XL

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Cast button 

Thank you

**Comment by Gamerx007** [comment]
> **Bug description**
> I updated yesterday to latest Manager and lasted Vanced version. YouTube won't run unless you update Google Play Services.
> I checked and everything is updated in Google Playstore..
> 
> **Variant**
> Non-Root
> 
> **Vanced version**
> 16.16.38
> 
> **Android version**
> Android 11.0 - Android R
> 
> **Device**
> Google Pixel 3XL
> 
> **Steps to Reproduce**
> Steps to reproduce the error:
> 
> 1. Open the app
> 2. Click on Cast button
> 
> Thank you
----------------------------------------------------------------------------------------------------------------------------------------------

( Known issues: )
- casting still broken on non-root due to micro G, it will need to be patched upstream first or a bypass will need to be found, use stock youtube for now or root vanced ( vanced does not block casting ads) )
- 
- this was in the Announcements section 
Yes this is still Broken for the Latest Version of Vanced and it is mainly because A workaround or a patch has not been found yet for Micro G

**Comment by JDMorris81** [comment]
Same issue here on Galaxy S20 5G.

**Comment by KevinX8** [comment]
Duplicate
