### ISSUE TITLE
[Bug] Vanced Auto quality does Not set the chosen Video Quality

### ISSUE THREAD

**Issue by BlueStarBRS** [YTVanced/Vanced#835]
**Bug description**
If you go in vanced settings and change the Video Auto quality for mobile or wifi it does not set it on the video ...again (its a old bug who is back)

**Variant**
Non-Root

**Vanced version*
16.16.38 

**Android version**
Android 8.0 - Oreo

**Device**
Samsung Galaxy A5 (2017)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on vanced Settings
3. Click on Video settings
4. set Quality for mobile and WiFi
5. go on a video with WiFi or Mobile and you see the app Takes a random Quality and ignores your settings

**Expected behavior**
I think its this YouTube video Settings from the Original app self who corrupted the vanced video Settings Control (vanced video settings are mush better)
And yes this bug is AGAIN in vanced last time it whas with the Video Settings function (beta) now its again in but not beta but same bug.

This triggers the bug↓
![Screenshot_20210518-142449.jpg](https://user-images.githubusercontent.com/25110093/118659120-5409e980-b7ed-11eb-9e0e-594e7e87c4a4.jpg)

↓This function dont work with if the YouTube original video settings are in the app
![Screenshot_20210518-142517.jpg](https://user-images.githubusercontent.com/25110093/118659164-5cfabb00-b7ed-11eb-8880-36c101c619db.jpg)

In this Screenshot you see a older Version 16.2.38 (i downgrade my vanced) and here it works on WiFi 1080p and mobile 360p 
![Screenshot_20210518-144250.jpg](https://user-images.githubusercontent.com/25110093/118657761-09d43880-b7ec-11eb-8372-918599617cb0.jpg)

**Comment by BlueStarBRS** [comment]
Contact me for questions

**Comment by milindgoel15** [comment]
Your screenshots literally says it's working fine. You set 1080p on wifi and you the same 1080p while watching videos. Such a invalid and useless report

**Comment by BlueStarBRS** [comment]
> Your screenshots literally says it's working fine. You set 1080p on wifi and you the same 1080p while watching videos. Such a invalid and useless report

maybe you are blind the app ignores the quality what i select! thanks onb the yt impemented auto video shit!

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/121935867-3f1b6a00-cd49-11eb-9b61-c1a680450015.png)
😡

**Comment by milindgoel15** [comment]
Again for the last time, look at it yourself. It was working even on v16.16 and it still does on V16.20

![Screenshot_20210614-232733_YouTube.png](https://user-images.githubusercontent.com/45682747/121937473-57e74800-cd68-11eb-9e6c-1189acec01ea.png)

![Screenshot_20210614-232738_YouTube.png](https://user-images.githubusercontent.com/45682747/121937486-5cabfc00-cd68-11eb-9321-c228b3aefdbd.png)

![Screenshot_20210614-232759_YouTube.png](https://user-images.githubusercontent.com/45682747/121937500-5fa6ec80-cd68-11eb-93d9-b348b6b568b2.png)

The vanced preferred quality literally got fixed with v16.16.38 release when google broke it on v16.14. If you have some better and useful information, tell that. Otherwise update to the latest version when reporting your issues. Issues from older versions are not accepted anyway.
