### ISSUE TITLE
Youtube Vanced Insists No Connection

### ISSUE THREAD

**Issue by ClayStation2** [YTVanced/Vanced#836]
All Youtube Vanced does for me is tell me to connect to the internet. If you can read this, then I damn well AM connected. WTF? I downloaded and installed the latest version, I have a screaming fast WiFi connection, and set unlimited data connection permission for it, what else can I try?

**Comment by gghhkm** [comment]
Check your Internet 😜







### General fix for everything Non-root: 
• this will fix most nonroot Vanced related issues
• you can consider this the proper Vanced install method



#### Preparations for clean install
• if you've already installed it and have problems, otherwise Skip.
1. Remove the microG account from system settings.
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

#### Installation
1. Make sure you're using Vanced Manager 2.5.0 or above. SAI method will also work.
(MiUi users disable MiUi optimization too)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use https://dontkillmyapp.com/ if needed.
4. Install Vanced &/or Music (Note : as of 16.14.34 login bug should be fixed.)
5. Login 
(MiUi users, you can readable MiUi optimization at this point if you have to)
