### ISSUE TITLE
[Idea] Preferred Speed Per Channel

### ISSUE THREAD

**Issue by nochlab1** [YTVanced/Vanced#874]
Be able to decide preferred speed for specific channels as some channels i like x1 and some i like x2

**Comment by Sebastian7700** [comment]
In my opinion, changing the video speed is done so often, that it is one of the most basic enhancing features and therefore would bring a massive value to the users if being implemented in a better way by the Vanced Team. And improving YT seems to be the mission of YT Vanced.

**Cumulation of issues [ideas]:**
1. #1571 Most people only go into settings to change video speed. It is nested there by YT so that you don't change it and spend more time on their platform. There is enough space for a quick toggle and I think it's a great idea. You can change the preferred video speed in the Vanced settings, but then you often find videos where you have to change it back and this is even more annoying.

2. #939 This essentially is the same thing. You could add an option in the settings on how this button should behave. Eighter "switchover all speeds" or "toggle to preferred speed".

3. #874 I originally came to this GitHub page to request this feature. This would save even more time and would be absolutely awesome and incredible. I would implement it in a way that when you press on the three dots on the top right of a video, next to all the settings another option appears, which is called "Save current speed as default for this channel."

4. #1602 This goes hand in hand with the first point. It is really annoying to set a preferred video speed and always in the morning when you listen to music you have to change it back. Eighter way even if you only listen once a week to music I think it is safe to say that nobody wants to listen on 2x. (Overall I think the preferred speed per channel is way superior to this feature but wanted to mention it anyway)

Thank you to the developers for making YT Vanced such a great experience, hope in the future it will become even better.
Have a great day!

_P.S. To devs, if you want me to open a new issue with this, please say so._

**Comment by milindgoel15** [comment]
Please refer issue #1602 from now on.
