### ISSUE TITLE
[Question] I couldn't find any Privacy Policy

### ISSUE THREAD

**Issue by atahabaki** [YTVanced/Vanced#879]
Hi, it would be nice to see a "Privacy Policy". This is necessary 'cause a lot of people of your community is questioning about whether YTVanced collects data or not, and I'm included. Adding that would help to expand your community...

**Comment by milindgoel15** [comment]
Vanced doesn't have its own privacy policy because it only mods the YouTube app on Android with adblocking and background playback. That's why vanced is purely stock yt + vanced patch. Vanced doesn't collect any data of anyone. 

For all other info, please [read this](https://telegra.ph/Vanced-05-11)

**Comment by atahabaki** [comment]
Thanks. 👍
