### ISSUE TITLE
[Idea] Allow to disable youtube's automatic title translation

### ISSUE THREAD

**Issue by HRudyPlayZ** [YTVanced/Vanced#908]
**Description**
Everything's in the title.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
There is this extension for Chrome that does this on PC:
https://github.com/zpix1/yt-anti-translate

**Comment by Harmonie666** [comment]
This would be great. I hate it when YT autotranslates titles based on my phone's system language. 
I do understand English titles, and some other languages aswell, and I want to keep their original title language and description ffs!

**Comment by jaambo** [comment]
> 
> 
> This would be great. I hate it when YT autotranslates titles based on my phone's system language.
> I do understand English titles, and some other languages aswell, and I want to keep their original title language and description ffs!

I completely agree! Have the same opinion. Sometimes there're completely stupid translations.

**Comment by DraconicNEO** [comment]
I really hope this is added, My phone doesn't support my Native language so YouTube usually auto translates all titles to English.

**Comment by DraconicNEO** [comment]
@milindgoel15 Just in case you aren't aware there is [a browser addon that does this](https://github.com/zpix1/yt-anti-translate). Maybe it would be worth looking into this since it wouldn't necessarily need to be done completely from scratch.

**Comment by milindgoel15** [comment]
I think we need to remind you again and again that browser add-ons/extensions aren't made for android clients. Android clients are not written on web based technologies/languages. And since this is YouTube, major code is obfuscated and written in litho. 

If you all have a better solution, you can come up with that. Or you all can try to code such solution into YouTube app and we will appreciate the contribution done.

Till that time, the issue is closed and should be requested from Google instead.

**Comment by DraconicNEO** [comment]
Sorry, I won't do it again.
