### ISSUE TITLE
[Idea] add x2 speed button option in player overlay

### ISSUE THREAD

**Issue by nochlab1** [YTVanced/Vanced#939]
I think there is enough space for another button on player overlay and it would be really nice as its the option i toggle the most

**Comment by functionOverlord** [comment]
@nochlab1 I just noticed there is a default playback speed setting under vanced settings > video settings > preferred video speed, maybe that solves the issue for you.

I still think there should be a separate button for playback speeds, because currently it takes too long with too many steps, and half the time I click "watch in VR" by accident or select the wrong speed and have to go back all over again which can be really annoying.

**Comment by ndm13** [comment]
I personally have my speed set to 1.5-2x globally, but occasionally I'll want to drop it down to 1x for things like music. A simple speed toggle button would be nice, to swap between 1x and whatever you define in the settings.

I'd personally prefer it in place of the autoplay toggle which I never use, but I know there's an open issue for hiding that already.

**Comment by milindgoel15** [comment]
Please refer issue #1602 from now on.
