### ISSUE TITLE
[Bug] Overheating 

### ISSUE THREAD

**Issue by xThory** [YTVanced/Vanced#964]
**Bug description**
I installed Vanced on 2 smartphones and also on the android stereo of my car. All 3 get hot with the use of vanced. In the old versions of a few months ago it didn't happen 

**Variant**
Non-Root

**Vanced version**
v16.14.34 build 1.50.01

**Android version**
Android 11 

**Device**
Samsung Galaxy S20 Plus/Honor View 10/Xtrons IB80A3AL

**Comment by milindgoel15** [comment]
Closing issue as the user is using old versions. Please update and use the latest v16.20 before reporting any type of issues. The battery drain/heating was already fixed with v16.16.38

**Comment by xThory** [comment]
I thought I had the latest because the advanced manager didn't notify any updates. Anyway I have updated but the overheating persists.

I got the phone cooled down, installed original youtube and signed up for the premium version for free for 1 month. After 1 hour of continuous background music, the phone did not warm up in the slightest. Fresh. So I think there is some problem with vanced .. it didn't happen in the past
________________________________

**Comment by milindgoel15** [comment]
Such issues was fixed with v16.16 release as I said earlier. Since we cannot say it's vanced issue, we would need screenshot of the vanced version you downloaded, plus the hash sha-256 value together-with logcat. If you don't know how to get logcat, read [this guide](https://play.google.com/store/apps/details?id=com.vanced.faq)

That will help us what exactly is causing heating issue on your device.
