### ISSUE TITLE
Vanced do not install/or update

### ISSUE THREAD

**Issue by Abonity** [YTVanced/Vanced#966]
when I tried to update YouTube vanced, it said it was unavailable, then I uninstalled it and then it didn't even appear to install, nor did the microg have the option to install it again, I'm using a Lenovo z6 lite, Android 9
the problem happens when I'm going to update, or in this case, reinstall vanced, so just go to vanced manager, and try to update vanced

**Comment by Abonity** [comment]
![Screenshot_2021-06-14-09-03-27-1057832940](https://user-images.githubusercontent.com/83374077/121890783-19627680-ccf1-11eb-9d50-65fac6d952f1.png)

**Comment by milindgoel15** [comment]
The server has blocked some IPs to communicate with servers due to numerous people trying to download vanced at the same time. This happened due to the notification regarding the update release pushed to indian region as we are doing staged roll out via manager to different parts of the world.

Hence you are required to wait for few hours until everything sets out. So be patient.
